import fs from 'fs'
import path from 'path'
import ignore from 'ignore'
import { program } from 'commander'

// Read package.json for version and metadata
let pkgStr = '{}'
try {
    const pkgPath = new URL('../package.json', import.meta.url)
    pkgStr = fs.readFileSync(pkgPath, 'utf8')
} catch (e) {
    try {
        // Fallback for when running via vite-node locally
        pkgStr = fs.readFileSync('./package.json', 'utf8')
    } catch(e2) {
        // ignore
    }
}
const pkg = JSON.parse(pkgStr)
const VERSION = pkg.version || 'unknown'
const TOOL_NAME = pkg.name || '@json-express/context-builder'

program
    .name('context-builder')
    .description('A cli tool to build your project context that can be uploaded to ai when chatting')
    .version(VERSION, '-v, --version', 'output the current version')
    .argument('[paths...]', 'Paths (directories or files) to include in the context. Defaults to current directory if none specified.')
    .option('-o, --out <directory>', 'Output directory', '.')
    .option('-n, --name <filename>', 'Output filename (default dynamic based on format)')
    .option('-f, --format <format>', 'Output format (md, txt, json)', 'md')
    .option('-c, --compress', 'Compress output to save LLM tokens by removing whitespace and comments', false)
    .option('--copy', 'Skip creating a file and only copy the context to clipboard', false)
    .action(async (paths, options) => {
        const startPaths = paths.length > 0 ? paths : ['.']

        let outDir = options.out
        // Handle common UX mistake where user might input `./dist` instead of `dist`
        if (outDir.startsWith('./') && outDir.length > 2) {
            outDir = outDir.slice(2)
        }

        const format = options.format.toLowerCase()
        if (!['md', 'txt', 'json'].includes(format)) {
            console.error('Invalid format specified. Must be md, txt, or json.')
            process.exit(1)
        }

        const outName = options.name || `llm-context.${format}`
        const outputFilePath = path.join(outDir, outName)
        const isCompress = options.compress
        const isCopyOnly = options.copy

        // Ensure output directory exists
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true })
        }

        // --- Ignore Logic Setup ---

        // 1. gitIg: For full exclusion from tree and content
        const gitIg = ignore()

        const gitignorePath = '.gitignore'
        if (fs.existsSync(gitignorePath)) {
            const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8')
            gitIg.add(gitignoreContent)
        }
        gitIg.add('node_modules')
        // Automatically ignore the output file so it doesn't try to read itself
        gitIg.add(outName)
        gitIg.add('.git')

        // 2. contextIg: For content-only exclusion
        const contextIg = ignore()
        const contextIgnorePath = '.contextignore'
        if (fs.existsSync(contextIgnorePath)) {
            const contextIgnoreContent = fs.readFileSync(contextIgnorePath, 'utf8')
            contextIg.add(contextIgnoreContent)
        }

        // --- Main Script Logic ---

        let finalOutputString = ''

        // Write the main AI Prompt
        const aiPrompt = `This is a codebase context file generated by ${TOOL_NAME} (v${VERSION}).
It contains a file tree followed by the contents of the files.
Note that some files might be omitted based on project constraints (.gitignore and .contextignore).
If you need to see the contents of any files listed in the tree that are omitted from the content section (e.g., due to .contextignore), please ask me.

================================================================================
`

        // Data structure for JSON format
        const jsonOutput = {
            tool: TOOL_NAME,
            version: VERSION,
            trees: [],
            files:[]
        }

        if (format === 'md' || format === 'txt') {
            finalOutputString += aiPrompt + '\n'
        }

        const generateTree = (dir, prefix = '') => {
            if (!fs.existsSync(dir)) return ''

            if (fs.statSync(dir).isFile()) {
                return ''
            }

            const allFiles = fs.readdirSync(dir)
            const allowedFiles = allFiles.filter(file => {
                const absolutePath = path.resolve(dir, file)
                const relativePath = path.relative(process.cwd(), absolutePath)
                return !gitIg.ignores(relativePath)
            })

            let tree = ''
            allowedFiles.forEach((file, index) => {
                const filePath = path.join(dir, file)
                const absolutePath = path.resolve(filePath)
                const relativePath = path.relative(process.cwd(), absolutePath)

                const isItemIgnored = gitIg.ignores(relativePath)
                if (isItemIgnored) return;

                const isLast = index === allowedFiles.length - 1
                const connector = isLast ? '└── ' : '├── '

                tree += `${prefix}${connector}${file}\n`

                if (fs.statSync(filePath).isDirectory()) {
                    const newPrefix = prefix + (isLast ? '    ' : '│   ')
                    tree += generateTree(filePath, newPrefix)
                }
            })
            return tree
        }

        const compressContent = (content, ext) => {
            if (!isCompress) return content;

            let compressed = content;

            const cLikeExtensions =['js', 'jsx', 'ts', 'tsx', 'java', 'c', 'cpp', 'cs', 'go', 'php', 'swift', 'kt'];
            const hashExtensions =['py', 'rb', 'yaml', 'yml', 'sh', 'pl', 'r'];
            const htmlExtensions =['html', 'xml', 'vue', 'svelte', 'svg'];

            if (cLikeExtensions.includes(ext)) {
                // Remove multi-line comments
                compressed = compressed.replace(/\/\*[\s\S]*?\*\//g, '');
                // Remove single-line comments safely
                compressed = compressed.replace(/(^\s*|\s+)\/\/.*$/gm, '');
            } else if (hashExtensions.includes(ext)) {
                // Remove Python/Ruby style comments #
                compressed = compressed.replace(/(^\s*|\s+)#.*$/gm, '');
            } else if (htmlExtensions.includes(ext)) {
                // Remove HTML comments <!-- -->
                compressed = compressed.replace(/<!--[\s\S]*?-->/g, '');
            }

            // Remove excessive blank lines for all files
            compressed = compressed.replace(/\n\s*\n/g, '\n');

            // Trim leading/trailing whitespace
            return compressed.trim();
        }

        const readPathAndWriteToFile = (itemPath) => {
            if (!fs.existsSync(itemPath)) return

            const absolutePath = path.resolve(itemPath)
            const relativePath = path.relative(process.cwd(), absolutePath)
            // Fallback to basename if the file is strictly outside cwd scope (preventing crashes)
            // If relativePath is '' it means itemPath IS the cwd (user passed '.' or no args).
            // The ignore library throws on empty strings, and the root scan target should never be ignored anyway.
            const relativeCheckPath = relativePath.startsWith('..') ? path.basename(itemPath) : relativePath

            if (relativeCheckPath && gitIg.ignores(relativeCheckPath)) {
                return
            }

            const stat = fs.statSync(itemPath)

            if (stat.isDirectory()) {
                const files = fs.readdirSync(itemPath)
                files.forEach(file => {
                    readPathAndWriteToFile(path.join(itemPath, file))
                })
            } else if (stat.isFile()) {
                if (contextIg.ignores(relativeCheckPath)) {
                    return
                } else {
                    const rawContent = fs.readFileSync(itemPath, 'utf8')
                    // Use the relative path for the display string, but default to basename if it's completely out of bounds
                    const displayPath = relativePath.startsWith('..') ? itemPath : relativePath
                    const ext = path.extname(itemPath).slice(1) || 'text'
                    const content = compressContent(rawContent, ext)

                    if (format === 'json') {
                        jsonOutput.files.push({
                            path: displayPath,
                            content: content
                        })
                    } else if (format === 'md') {
                        const outputContent = `### ${displayPath}\n\`\`\`${ext}\n${content}\n\`\`\`\n\n`
                        finalOutputString += outputContent
                    } else {
                        // Plain text formatting
                        const outputContent = `${displayPath}\n----------------------------------------\n${content}\n\n========================================\n\n`
                        finalOutputString += outputContent
                    }
                }
            }
        }

        // --- Execution ---

        console.log('Generating file tree(s)...')

        // Step 1: Generate all file trees and output them first
        startPaths.forEach(p => {
            const treeStructure = generateTree(p)
            const rootName = p === '.' ? path.basename(process.cwd()) : path.basename(p)

            if (format === 'json') {
                jsonOutput.trees.push({
                    directory: rootName,
                    tree: treeStructure
                })
            } else if (format === 'md') {
                finalOutputString += `## Project Tree: ${rootName}\n\`\`\`text\n${rootName}\n${treeStructure}\n\`\`\`\n\n`
            } else {
                finalOutputString += `Project Tree: ${rootName}\n${treeStructure}\n\n`
            }
        })

        console.log('Generating file contents...')

        // Step 2: Append all file contents below the generated trees
        startPaths.forEach(p => {
            console.log(`Processing path: ${p}`)
            readPathAndWriteToFile(p)
        })

        // Step 3: Serialize JSON if needed
        if (format === 'json') {
            finalOutputString = JSON.stringify(jsonOutput, null, 2)
        }

        const finalizeOutput = async () => {
            try {
                const clipboardy = (await import('clipboardy')).default;
                clipboardy.writeSync(finalOutputString);

                if (isCopyOnly) {
                    console.log(`Processing complete. The context has been copied to your clipboard (skipping file creation).`)
                } else {
                    fs.writeFileSync(outputFilePath, finalOutputString);
                    console.log(`Processing complete. The output has been written to ${outputFilePath} AND copied to your clipboard.`)
                }
            } catch (err) {
                console.error('Failed to copy to clipboard or write file:', err.message)
                if (!isCopyOnly) {
                    fs.writeFileSync(outputFilePath, finalOutputString);
                    console.log(`Processing complete. The output has been written to ${outputFilePath} (Clipboard copy failed).`)
                }
            }
        }

        await finalizeOutput()
    })

program.parse(process.argv)
