import fs from 'fs'
import path from 'path'
import ignore from 'ignore'
import { program } from 'commander'

// Read package.json for version and metadata
let pkgStr = '{}'
try {
    const pkgPath = new URL('../package.json', import.meta.url)
    pkgStr = fs.readFileSync(pkgPath, 'utf8')
} catch (e) {
    try {
        // Fallback for when running via vite-node locally
        pkgStr = fs.readFileSync('./package.json', 'utf8')
    } catch(e2) {
        // ignore
    }
}
const pkg = JSON.parse(pkgStr)
const VERSION = pkg.version || 'unknown'
const TOOL_NAME = pkg.name || '@json-express/context-builder'

program
    .name('context-builder')
    .description('A cli tool to build your project context that can be uploaded to ai when chatting')
    .version(VERSION, '-v, --version', 'output the current version')
    .argument('[directories...]', 'Directories to include in the context. Defaults to current directory if none specified.')
    .option('-o, --out <directory>', 'Output directory', '.')
    .option('-n, --name <filename>', 'Output filename', 'project-context.txt')
    .action((directories, options) => {
        const startDirs = directories.length > 0 ? directories : ['.']
        
        let outDir = options.out
        // Handle common UX mistake where user might input `./dist` instead of `dist`
        if (outDir.startsWith('./') && outDir.length > 2) {
            outDir = outDir.slice(2)
        }
        
        const outputFilePath = path.join(outDir, options.name)

        // Ensure output directory exists
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true })
        }

        // --- Ignore Logic Setup ---

        // 1. gitIg: For full exclusion from tree and content
        const gitIg = ignore()

        // Add default and .gitignore rules
        const gitignorePath = '.gitignore'
        if (fs.existsSync(gitignorePath)) {
            const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8')
            gitIg.add(gitignoreContent)
        }
        gitIg.add('node_modules')
        // Automatically ignore the output file so it doesn't try to read itself
        gitIg.add(options.name) 
        gitIg.add('.git')

        // 2. contextIg: For content-only exclusion
        const contextIg = ignore()
        const contextIgnorePath = '.contextignore'
        if (fs.existsSync(contextIgnorePath)) {
            const contextIgnoreContent = fs.readFileSync(contextIgnorePath, 'utf8')
            contextIg.add(contextIgnoreContent)
        }

        // --- Main Script Logic ---

        try {
            fs.writeFileSync(outputFilePath, '')
        } catch (err) {
            console.error(`Error clearing/creating output file: ${err.message}`)
            process.exit(1)
        }
        
        // Write the main AI Prompt
        const aiPrompt = `This is a codebase context file generated by ${TOOL_NAME} (v${VERSION}).
It contains a file tree followed by the contents of the files.
Note that some files might be omitted based on project constraints (.gitignore and .contextignore).
If you need to see the contents of any files listed in the tree that are omitted from the content section (e.g., due to .contextignore), please ask me.

================================================================================
`
        fs.appendFileSync(outputFilePath, aiPrompt + '\n')

        const generateTree = (dir, prefix = '') => {
            if (!fs.existsSync(dir)) return ''
            
            const allFiles = fs.readdirSync(dir)
            // The tree is only affected by .gitignore rules
            const allowedFiles = allFiles.filter(file => !gitIg.ignores(path.join(dir, file).replace(/^\.\//, '')))

            let tree = ''
            allowedFiles.forEach((file, index) => {
                const filePath = path.join(dir, file)
                const isItemIgnored = gitIg.ignores(filePath.replace(/^\.\//, ''))
                if (isItemIgnored) return;

                const isLast = index === allowedFiles.length - 1
                const connector = isLast ? '└── ' : '├── '

                tree += `${prefix}${connector}${file}\n`

                if (fs.statSync(filePath).isDirectory()) {
                    const newPrefix = prefix + (isLast ? '    ' : '│   ')
                    tree += generateTree(filePath, newPrefix)
                }
            })
            return tree
        }

        const readDirectoryAndWriteToFile = (directoryPath) => {
            if (!fs.existsSync(directoryPath)) return
            
            const files = fs.readdirSync(directoryPath)

            files.forEach(file => {
                const filePath = path.join(directoryPath, file)
                const normalizedPath = filePath.replace(/^\.\//, '')

                // First, check for full exclusion from .gitignore
                if (gitIg.ignores(normalizedPath)) {
                    return
                }

                const stat = fs.statSync(filePath)

                if (stat.isDirectory()) {
                    readDirectoryAndWriteToFile(filePath)
                } else if (stat.isFile()) {
                    // Next, check for content-only exclusion from .contextignore
                    if (contextIg.ignores(normalizedPath)) {
                        // Do NOT print anything for context-ignored files
                        return
                    } else {
                        // Otherwise, list the path and the content
                        const content = fs.readFileSync(filePath, 'utf8')
                        const outputContent = `${normalizedPath}\n\`\`\`\n${content}\n\`\`\`\n\n`
                        fs.appendFileSync(outputFilePath, outputContent)
                    }
                }
            })
        }

        // --- Execution ---

        console.log('Generating file tree and content...')

        startDirs.forEach(dir => {
            console.log(`Processing directory: ${dir}`)
            
            // 1. Generate and write the tree structure (respects .gitignore)
            const treeStructure = generateTree(dir)
            const rootName = dir === '.' ? path.basename(process.cwd()) : path.basename(dir)
            
            fs.appendFileSync(outputFilePath, rootName + '\n' + treeStructure + '\n\n')

            // 2. Read and write file content (respects both .gitignore and .contextignore)
            readDirectoryAndWriteToFile(dir)
        })

        console.log(`Processing complete. The output has been written to ${outputFilePath}`)
    })

program.parse(process.argv)
