import fs from 'fs'
import path from 'path'
import ignore from 'ignore'
import { program } from 'commander'

// Read package.json for version and metadata
let pkgStr = '{}'
try {
    const pkgPath = new URL('../package.json', import.meta.url)
    pkgStr = fs.readFileSync(pkgPath, 'utf8')
} catch (e) {
    try {
        // Fallback for when running via vite-node locally
        pkgStr = fs.readFileSync('./package.json', 'utf8')
    } catch(e2) {
        // ignore
    }
}
const pkg = JSON.parse(pkgStr)
const VERSION = pkg.version || 'unknown'
const TOOL_NAME = pkg.name || '@json-express/context-builder'

program
    .name('context-builder')
    .description('A cli tool to build your project context that can be uploaded to ai when chatting')
    .version(VERSION, '-v, --version', 'output the current version')
    .argument('[directories...]', 'Directories to include in the context. Defaults to current directory if none specified.')
    .option('-o, --out <directory>', 'Output directory', '.')
    .option('-n, --name <filename>', 'Output filename (default dynamic based on format)')
    .option('-f, --format <format>', 'Output format (md, txt, json)', 'md')
    .option('-c, --compress', 'Compress output to save LLM tokens by removing whitespace and comments', false)
    .action((directories, options) => {
        const startDirs = directories.length > 0 ? directories : ['.']
        
        let outDir = options.out
        // Handle common UX mistake where user might input `./dist` instead of `dist`
        if (outDir.startsWith('./') && outDir.length > 2) {
            outDir = outDir.slice(2)
        }
        
        const format = options.format.toLowerCase()
        if (!['md', 'txt', 'json'].includes(format)) {
            console.error('Invalid format specified. Must be md, txt, or json.')
            process.exit(1)
        }

        const outName = options.name || `llm-context.${format}`
        const outputFilePath = path.join(outDir, outName)
        const isCompress = options.compress

        // Ensure output directory exists
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true })
        }

        // --- Ignore Logic Setup ---

        // 1. gitIg: For full exclusion from tree and content
        const gitIg = ignore()

        const gitignorePath = '.gitignore'
        if (fs.existsSync(gitignorePath)) {
            const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8')
            gitIg.add(gitignoreContent)
        }
        gitIg.add('node_modules')
        // Automatically ignore the output file so it doesn't try to read itself
        gitIg.add(outName) 
        gitIg.add('.git')

        // 2. contextIg: For content-only exclusion
        const contextIg = ignore()
        const contextIgnorePath = '.contextignore'
        if (fs.existsSync(contextIgnorePath)) {
            const contextIgnoreContent = fs.readFileSync(contextIgnorePath, 'utf8')
            contextIg.add(contextIgnoreContent)
        }

        // --- Main Script Logic ---

        try {
            fs.writeFileSync(outputFilePath, '')
        } catch (err) {
            console.error(`Error clearing/creating output file: ${err.message}`)
            process.exit(1)
        }
        
        // Write the main AI Prompt
        const aiPrompt = `This is a codebase context file generated by ${TOOL_NAME} (v${VERSION}).
It contains a file tree followed by the contents of the files.
Note that some files might be omitted based on project constraints (.gitignore and .contextignore).
If you need to see the contents of any files listed in the tree that are omitted from the content section (e.g., due to .contextignore), please ask me.

================================================================================
`
        
        // Data structure for JSON format
        const jsonOutput = {
            tool: TOOL_NAME,
            version: VERSION,
            trees: [],
            files: []
        }

        if (format === 'md' || format === 'txt') {
            fs.appendFileSync(outputFilePath, aiPrompt + '\n')
        }

        const generateTree = (dir, prefix = '') => {
            if (!fs.existsSync(dir)) return ''
            
            const allFiles = fs.readdirSync(dir)
            const allowedFiles = allFiles.filter(file => !gitIg.ignores(path.join(dir, file).replace(/^\.\//, '')))

            let tree = ''
            allowedFiles.forEach((file, index) => {
                const filePath = path.join(dir, file)
                const isItemIgnored = gitIg.ignores(filePath.replace(/^\.\//, ''))
                if (isItemIgnored) return;

                const isLast = index === allowedFiles.length - 1
                const connector = isLast ? '└── ' : '├── '

                tree += `${prefix}${connector}${file}\n`

                if (fs.statSync(filePath).isDirectory()) {
                    const newPrefix = prefix + (isLast ? '    ' : '│   ')
                    tree += generateTree(filePath, newPrefix)
                }
            })
            return tree
        }

        const compressContent = (content, ext) => {
            if (!isCompress) return content;

            let compressed = content;

            const cLikeExtensions = ['js', 'jsx', 'ts', 'tsx', 'java', 'c', 'cpp', 'cs', 'go', 'php', 'swift', 'kt'];
            const hashExtensions = ['py', 'rb', 'yaml', 'yml', 'sh', 'pl', 'r'];
            const htmlExtensions = ['html', 'xml', 'vue', 'svelte', 'svg'];

            if (cLikeExtensions.includes(ext)) {
                // Remove multi-line comments: /* ... */ 
                // Using [\s\S]*? to match across newlines lazily
                compressed = compressed.replace(/\/\*[\s\S]*?\*\//g, '');
                // Remove single-line comments: // ... it's unsafe to blindly remove // inside strings so we do a simple regex that requires it to be at start of line or preceded by whitespace
                compressed = compressed.replace(/(^\s*|\s+)\/\/.*$/gm, '');
            } else if (hashExtensions.includes(ext)) {
                // Remove Python/Ruby style comments #
                compressed = compressed.replace(/(^\s*|\s+)#.*$/gm, '');
            } else if (htmlExtensions.includes(ext)) {
                // Remove HTML comments <!-- -->
                compressed = compressed.replace(/<!--[\s\S]*?-->/g, '');
            }

            // Remove excessive blank lines for all files
            compressed = compressed.replace(/\n\s*\n/g, '\n');
            
            // Trim leading/trailing whitespace
            return compressed.trim();
        }

        const readDirectoryAndWriteToFile = (directoryPath) => {
            if (!fs.existsSync(directoryPath)) return
            
            const files = fs.readdirSync(directoryPath)

            files.forEach(file => {
                const filePath = path.join(directoryPath, file)
                const normalizedPath = filePath.replace(/^\.\//, '')

                if (gitIg.ignores(normalizedPath)) {
                    return
                }

                const stat = fs.statSync(filePath)

                if (stat.isDirectory()) {
                    readDirectoryAndWriteToFile(filePath)
                } else if (stat.isFile()) {
                    if (contextIg.ignores(normalizedPath)) {
                        return
                    } else {
                        const rawContent = fs.readFileSync(filePath, 'utf8')
                        const ext = path.extname(normalizedPath).slice(1) || 'text'
                        const content = compressContent(rawContent, ext)
                        
                        if (format === 'json') {
                            jsonOutput.files.push({
                                path: normalizedPath,
                                content: content
                            })
                        } else if (format === 'md') {
                            const outputContent = `### ${normalizedPath}\n\`\`\`${ext}\n${content}\n\`\`\`\n\n`
                            fs.appendFileSync(outputFilePath, outputContent)
                        } else {
                            // Plain text formatting
                            const outputContent = `${normalizedPath}\n----------------------------------------\n${content}\n\n========================================\n\n`
                            fs.appendFileSync(outputFilePath, outputContent)
                        }
                    }
                }
            })
        }

        // --- Execution ---

        console.log('Generating file tree and content...')

        startDirs.forEach(dir => {
            console.log(`Processing directory: ${dir}`)
            
            const treeStructure = generateTree(dir)
            const rootName = dir === '.' ? path.basename(process.cwd()) : path.basename(dir)
            
            if (format === 'json') {
                jsonOutput.trees.push({
                    directory: rootName,
                    tree: treeStructure
                })
            } else if (format === 'md') {
                fs.appendFileSync(outputFilePath, `## Project Tree: ${rootName}\n\`\`\`text\n${rootName}\n${treeStructure}\n\`\`\`\n\n`)
                // Write directory files
                readDirectoryAndWriteToFile(dir)
            } else {
                fs.appendFileSync(outputFilePath, `Project Tree: ${rootName}\n${treeStructure}\n\n`)
                // Write directory files
                readDirectoryAndWriteToFile(dir)
            }
        })

        if (format === 'json') {
            // Write JSON structure
            startDirs.forEach(dir => readDirectoryAndWriteToFile(dir))
            fs.writeFileSync(outputFilePath, JSON.stringify(jsonOutput, null, 2))
        }

        console.log(`Processing complete. The output has been written to ${outputFilePath}`)
    })

program.parse(process.argv)
